# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170106_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytopost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorytopost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryToPost',
        ),
    ]
