# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20170106_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
