# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_remove_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationsPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum.Post')),
            ],
            bases=('forum.post',),
        ),
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
